#pragma once

#include <stdint.h>

/*
 * The MMIO layout is shared by the host device model and the guest driver.
 * The address is intentionally outside the current guest RAM memslot, so a
 * guest access becomes KVM_EXIT_MMIO and is handled by the VMM.
 */
#define VIRTIO_MMIO_BASE_GPA UINT64_C(0x01000000)
#define VIRTIO_MMIO_SIZE     UINT32_C(0x1000)

#define VIRTIO_MMIO_MAGIC_VALUE UINT32_C(0x74726976)
#define VIRTIO_MMIO_VERSION     UINT32_C(2)
#define VIRTIO_MMIO_DEVICE_NET  UINT32_C(1)
#define VIRTIO_MMIO_VENDOR_ID   UINT32_C(0x554d4554) /* "UMET" */

/* The minimal VMM injects this vector directly with KVM_INTERRUPT. */
#define VIRTIO_NET_INTERRUPT_VECTOR UINT32_C(32)

/* Virtio MMIO common registers. */
#define VIRTIO_MMIO_REG_MAGIC_VALUE      UINT32_C(0x000)
#define VIRTIO_MMIO_REG_VERSION          UINT32_C(0x004)
#define VIRTIO_MMIO_REG_DEVICE_ID        UINT32_C(0x008)
#define VIRTIO_MMIO_REG_VENDOR_ID        UINT32_C(0x00c)
#define VIRTIO_MMIO_REG_DEVICE_FEATURES  UINT32_C(0x010)
#define VIRTIO_MMIO_REG_DEVICE_FEATURES_SEL UINT32_C(0x014)
#define VIRTIO_MMIO_REG_DRIVER_FEATURES  UINT32_C(0x020)
#define VIRTIO_MMIO_REG_DRIVER_FEATURES_SEL UINT32_C(0x024)
#define VIRTIO_MMIO_REG_QUEUE_SEL        UINT32_C(0x030)
#define VIRTIO_MMIO_REG_QUEUE_NUM_MAX    UINT32_C(0x034)
#define VIRTIO_MMIO_REG_QUEUE_NUM        UINT32_C(0x038)
#define VIRTIO_MMIO_REG_QUEUE_READY      UINT32_C(0x044)
#define VIRTIO_MMIO_REG_QUEUE_NOTIFY     UINT32_C(0x050)
#define VIRTIO_MMIO_REG_INTERRUPT_STATUS UINT32_C(0x060)
#define VIRTIO_MMIO_REG_INTERRUPT_ACK    UINT32_C(0x064)
#define VIRTIO_MMIO_REG_STATUS            UINT32_C(0x070)
#define VIRTIO_MMIO_REG_QUEUE_DESC_LOW    UINT32_C(0x080)
#define VIRTIO_MMIO_REG_QUEUE_DESC_HIGH   UINT32_C(0x084)
#define VIRTIO_MMIO_REG_QUEUE_DRIVER_LOW  UINT32_C(0x090)
#define VIRTIO_MMIO_REG_QUEUE_DRIVER_HIGH UINT32_C(0x094)
#define VIRTIO_MMIO_REG_QUEUE_DEVICE_LOW  UINT32_C(0x0a0)
#define VIRTIO_MMIO_REG_QUEUE_DEVICE_HIGH UINT32_C(0x0a4)
#define VIRTIO_MMIO_REG_CONFIG_GENERATION UINT32_C(0x0fc)
#define VIRTIO_MMIO_REG_CONFIG_SPACE      UINT32_C(0x100)

/* Device status bits. */
#define VIRTIO_STATUS_ACKNOWLEDGE UINT8_C(0x01)
#define VIRTIO_STATUS_DRIVER     UINT8_C(0x02)
#define VIRTIO_STATUS_DRIVER_OK  UINT8_C(0x04)
#define VIRTIO_STATUS_FEATURES_OK UINT8_C(0x08)
#define VIRTIO_STATUS_FAILED     UINT8_C(0x80)

/* Feature bit numbers used by this small device. */
#define VIRTIO_F_VERSION_1 UINT32_C(32)
#define VIRTIO_NET_F_MAC   UINT32_C(5)

/* Virtqueue descriptor flags. */
#define VIRTQ_DESC_F_NEXT  UINT16_C(1)
#define VIRTQ_DESC_F_WRITE UINT16_C(2)
